name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install CocoaPods (if needed)
        run: |
          cd CDImplementation
           pod install

      - name: Build for simulator
        run: |
              xcodebuild clean build \
              -workspace CDImplementation/CDImplementation.xcworkspace \
              -scheme CDImplementation \
              -destination 'platform=iOS Simulator,name=iPhone 18.4'

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -workspace CDImplementation.xcworkspace \
            -scheme CDImplementation \
            -destination 'platform=iOS Simulator,name=iPhone 15'

